In [1]:
import re
import pcre2
from formulaic.parser import DefaultFormulaParser
import anndata as ad

In [2]:
formula = "~disease_class+age+pc1"

In [3]:
[token.token for token in DefaultFormulaParser().get_tokens(formula) if token.kind.value == "name"]

['disease_class', 'age', 'pc1']

In [4]:
adata = ad.read_h5ad("/home/milo/workspace/memory_b.h5ad")

In [8]:
import formulaic_contrasts

In [10]:
dm = formulaic_contrasts.FormulaicContrasts(adata.obs, "~disease_class+age+pc1")

In [13]:
adata.obs.dtypes

n_genes_by_counts       int32
total_counts          float32
total_counts_mt       float32
pct_counts_mt         float32
sample               category
sample_name          category
visit_ref            category
subject_ref          category
disease_class        category
ethnicity            category
batch                category
leiden               category
type_label           category
leiden_wnn           category
level1_labels        category
level2_labels        category
level3_labels        category
self_race            category
age                     int64
pc1                   float64
dtype: object

In [14]:
import numpy as np

In [15]:
np.linalg.matrix_rank(dm.design_matrix)

np.int64(6)

In [16]:
dm.design_matrix.shape[1]

6

In [11]:
dm.design_matrix

,Intercept,disease_class[T.Neg],disease_class[T.Pos],disease_class[T.SLE],age,pc1
AAACGGGAGTCCGGTC-1_PAM46,1.0,0,0,0,50,0.133658
AAGGAGCGTTCAGTAC-1_PAM46,1.0,0,0,0,50,0.133658
ACGGAGACAACACCTA-1_PAM46,1.0,0,0,0,50,0.133658
ACTGAGTCACAGACAG-1_PAM46,1.0,0,0,0,50,0.133658
AGAATAGAGAAGGACA-1_PAM46,1.0,0,0,0,50,0.133658
...,...,...,...,...,...,...
TTCTCCTTCCACTGGG-1_PAM27,1.0,0,1,0,65,-0.078247
TTGACTTGTACCTACA-1_PAM27,1.0,0,1,0,65,-0.078247
TTGCCGTTCCACGACG-1_PAM27,1.0,0,1,0,65,-0.078247
TTGGCAATCAACGGCC-1_PAM27,1.0,0,1,0,65,-0.078247
TTTACTGGTTGCCTCT-1_PAM27,1.0,0,1,0,65,-0.078247

In [17]:
adata.obs["age"] = adata.obs["age"].astype("category")

In [18]:
dm2 = formulaic_contrasts.FormulaicContrasts(adata.obs, "~disease_class+age+pc1")

In [19]:
np.linalg.matrix_rank(dm2.design_matrix)

np.int64(34)

In [20]:
dm2.design_matrix.shape[1]

34

In [21]:
dm2.design_matrix

,Intercept,disease_class[T.Neg],disease_class[T.Pos],disease_class[T.SLE],age[T.24],age[T.26],age[T.28],age[T.31],age[T.33],age[T.34],...,age[T.56],age[T.57],age[T.60],age[T.61],age[T.65],age[T.67],age[T.68],age[T.69],age[T.76],pc1
AAACGGGAGTCCGGTC-1_PAM46,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.133658
AAGGAGCGTTCAGTAC-1_PAM46,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.133658
ACGGAGACAACACCTA-1_PAM46,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.133658
ACTGAGTCACAGACAG-1_PAM46,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.133658
AGAATAGAGAAGGACA-1_PAM46,1.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.133658
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTCTCCTTCCACTGGG-1_PAM27,1.0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,-0.078247
TTGACTTGTACCTACA-1_PAM27,1.0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,-0.078247
TTGCCGTTCCACGACG-1_PAM27,1.0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,-0.078247
TTGGCAATCAACGGCC-1_PAM27,1.0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,-0.078247
TTTACTGGTTGCCTCT-1_PAM27,1.0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,-0.078247

In [18]:
stuff[0].kind

In [3]:
formula.split("+")

['~disease_class', 'age', 'pc1']

In [8]:
pat=pcre2.compile(r"[[:punct:]]")

In [5]:
re.findall(pat, formula)

['c', 'p', 'c']

In [9]:
pcre2.findall(pat, formula)

['~', '_', '+', '+']